# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'saveslotui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_saveedit(object):
    def setupUi(self, saveedit):
        saveedit.setObjectName("saveedit")
        saveedit.resize(374, 163)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(saveedit.sizePolicy().hasHeightForWidth())
        saveedit.setSizePolicy(sizePolicy)
        saveedit.setMinimumSize(QtCore.QSize(374, 163))
        saveedit.setWindowTitle("")
        self.gridLayout_2 = QtWidgets.QGridLayout(saveedit)
        self.gridLayout_2.setContentsMargins(2, 2, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.moneyEdit = QtWidgets.QLineEdit(saveedit)
        self.moneyEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.moneyEdit.setObjectName("moneyEdit")
        self.gridLayout_2.addWidget(self.moneyEdit, 5, 1, 1, 1)
        self.setCharacterNameButton = QtWidgets.QPushButton(saveedit)
        self.setCharacterNameButton.setObjectName("setCharacterNameButton")
        self.gridLayout_2.addWidget(self.setCharacterNameButton, 3, 2, 1, 1)
        self.setMoneyButton = QtWidgets.QPushButton(saveedit)
        self.setMoneyButton.setObjectName("setMoneyButton")
        self.gridLayout_2.addWidget(self.setMoneyButton, 5, 2, 1, 1)
        self.setExpButton = QtWidgets.QPushButton(saveedit)
        self.setExpButton.setObjectName("setExpButton")
        self.gridLayout_2.addWidget(self.setExpButton, 4, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(saveedit)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(saveedit)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.saveSlotIndexLable = QtWidgets.QLabel(saveedit)
        self.saveSlotIndexLable.setObjectName("saveSlotIndexLable")
        self.gridLayout_2.addWidget(self.saveSlotIndexLable, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(saveedit)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.gameDataHeaderLabel = QtWidgets.QLabel(saveedit)
        self.gameDataHeaderLabel.setObjectName("gameDataHeaderLabel")
        self.gridLayout_2.addWidget(self.gameDataHeaderLabel, 2, 1, 1, 1)
        self.importheaderButton = QtWidgets.QPushButton(saveedit)
        self.importheaderButton.setObjectName("importheaderButton")
        self.gridLayout_2.addWidget(self.importheaderButton, 2, 2, 1, 1)
        self.saveButton = QtWidgets.QPushButton(saveedit)
        self.saveButton.setEnabled(False)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout_2.addWidget(self.saveButton, 1, 2, 1, 1)
        self.characterNameEdit = QtWidgets.QLineEdit(saveedit)
        self.characterNameEdit.setObjectName("characterNameEdit")
        self.gridLayout_2.addWidget(self.characterNameEdit, 3, 1, 1, 1)
        self.saveFileNameLable = QtWidgets.QLabel(saveedit)
        self.saveFileNameLable.setObjectName("saveFileNameLable")
        self.gridLayout_2.addWidget(self.saveFileNameLable, 1, 1, 1, 1)
        self.expEdit = QtWidgets.QLineEdit(saveedit)
        self.expEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.expEdit.setObjectName("expEdit")
        self.gridLayout_2.addWidget(self.expEdit, 4, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(saveedit)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 5, 0, 1, 1)
        self.chipButton = QtWidgets.QPushButton(saveedit)
        self.chipButton.setObjectName("chipButton")
        self.gridLayout_2.addWidget(self.chipButton, 6, 1, 1, 1)
        self.itemButton = QtWidgets.QPushButton(saveedit)
        self.itemButton.setObjectName("itemButton")
        self.gridLayout_2.addWidget(self.itemButton, 7, 1, 1, 1)

        self.retranslateUi(saveedit)
        QtCore.QMetaObject.connectSlotsByName(saveedit)

    def retranslateUi(self, saveedit):
        _translate = QtCore.QCoreApplication.translate
        self.setCharacterNameButton.setText(_translate("saveedit", "Set"))
        self.setMoneyButton.setText(_translate("saveedit", "Set"))
        self.setExpButton.setText(_translate("saveedit", "Set"))
        self.label_6.setText(_translate("saveedit", "Experience:"))
        self.label.setText(_translate("saveedit", "GameData.dat header:"))
        self.saveSlotIndexLable.setText(_translate("saveedit", "TextLabel"))
        self.label_5.setText(_translate("saveedit", "Character name:"))
        self.gameDataHeaderLabel.setText(_translate("saveedit", "TextLabel"))
        self.importheaderButton.setText(_translate("saveedit", "Import"))
        self.saveButton.setText(_translate("saveedit", "Save"))
        self.saveFileNameLable.setText(_translate("saveedit", "TextLabel"))
        self.label_7.setText(_translate("saveedit", "Money:"))
        self.chipButton.setText(_translate("saveedit", "Edit Chips"))
        self.itemButton.setText(_translate("saveedit", "Edit Items"))

